### ISSUE TITLE
CD for LSTMs

### ISSUE THREAD

**Issue by tangxiangru** [FredericGodin/ContextualDecomposition-NLP#1]
I noticed that in the paper you said you implement CD for LSTMs, but I cannot find it in this code

**Comment by FredericGodin** [comment]
Because I was not the owner of that particular piece of code, I removed it from this codebase. However, you can still find it in the original author's repo. 
https://github.com/jamie-murdoch/ContextualDecomposition

**Comment by tangxiangru** [comment]
thanks so much
